void DoControl();
void read_but();
void read_enc();
void LoadParameters();
void DriveOutput();
void Off();
void Tune_Sp();
void TuneP();
void Run();
void TuneI();
void TuneD();
void setPWM();
void SaveParameters();
void StartAutoTune();
void FinishAutoTune();
void printPWM();
void setBacklight();
void EEPROM_writeDouble(int address, double value);
double EEPROM_readDouble(int address);